# Generated by Django 5.0.6 on 2024-09-05 20:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé à')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié à')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
