# Generated by Django 5.0.6 on 2024-09-09 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_alter_customuser_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='slug',
        ),
    ]
