# Generated by Django 5.1.1 on 2024-09-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0005_alter_resetpasswordtoken_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resetpasswordtoken',
            name='is_used',
        ),
        migrations.AddField(
            model_name='resetpasswordtoken',
            name='is_actif',
            field=models.BooleanField(default=True, verbose_name='est actif'),
        ),
    ]
