# Generated by Django 5.1.1 on 2024-09-13 13:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0006_remove_resetpasswordtoken_is_used_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpasswordtoken',
            name='key',
            field=models.CharField(default=uuid.uuid4, editable=False, verbose_name='clé'),
        ),
    ]
